'Enter string to encode:'
TOENCODE ← ⍞
BYTESVEC ← ⎕UCS TOENCODE
∇ ROTATE BYTESVEC
  'Encoded string:'
  ENCODED ← ''
  :For CHAR :In BYTESVEC
    :If (CHAR≥97∧CHAR≤109)∨(CHAR≥65∧CHAR≤77)
      ENCODED ← ENCODED, CHAR+13
    :ElseIf (CHAR≥110∧CHAR≤122)∨(CHAR≥78∧CHAR≤90)
      ENCODED ← ENCODED, CHAR-13
    :Else
      ENCODED ← ENCODED, CHAR
    :EndIf
  :EndFor
  ENCODEDSTRING ← ⎕UCS ENCODED
  ENCODEDSTRING
∇
ROTATE BYTESVEC